---
name: "show-merged"
version: "0.2.0"
usage: "show merged values"
description: "show the final content of .Values"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/merged.sh"
hooks:
  install: "$HELM_PLUGIN_DIR/merged.sh --help"
